###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# Author:
#  Lucas Vasconcelos - July/2022
# 
###############################################################################
---
- name: Change passphrase
  hosts: all
  collections:
  - name: ibm.ibm_zos_core
    version: 1.4.0-beta.1
    source: https://galaxy.ansible.com
  #collections:
    - ibm.ibm_zos_core#
  gather_facts: true
  environment: "{{ environment_vars }}"
  connection: ibm.ibm_zos_core.zos_ssh

  tasks:
    - name: Change passphrase
      zos_tso_command:
        commands: "PASSWORD PHRASE('{{ passphrase_current }}' '{{ passphrase_new }}')"
