###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# Author:
#  Lucas Vasconcelos - July/2022
# 
###############################################################################
--- 
- name: Change passphrase
  hosts: all
  collections:
    - ibm.ibm_zos_core.zos_ssh
  gather_facts: true
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Change passphrase
      zos_tso_command:
        commands: "PASSWORD PHRASE('{{ passphrase_current }}' '{{ passphrase_new }}')"
