###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# z/OS CIRATS Installation
#
# Author:
#  Lucas Vasconcelos - July/2022
# 
###############################################################################
---
- name: Change passphrase
  hosts: all
  gather_facts: true
  environment: "{{ environment_vars }}"

  tasks:
    - name: Change passphrase
      command: "PASSWORD PHRASE('{{ passphrase_current }}' '{{ passphrase_new }}')"
