###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
#
# Author:
#  Lucas Vasconcelos - July/2022
# 
###############################################################################
--- 
- name: Flags on
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Flags on
      zos_tso_command:
        commands: "F CNMS,INGAUTO ON('{{ taskname }}')SCOPE=ONLY FLAG=AUTOMATION OUTMODE=LINE"
