---
- name: Create ticket with notes
  hosts: all
  gather_facts: no
  connection: local

  tasks:
  - name: include vars
    include_vars: servicenow_incident_vars.yml

  - name: Create an Incidentt
    snow_record:
      state: present
      table: incidents
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "This is a test opened by Ansible"
    register: new_incident

  - debug: 
      var: new_incident.record
