--- 
- name: PRE-CHECK Snapshot
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: PRE-CHECK Snapshot
      zos_tso_command:
        commands: "F CNMS,SNAPSHOT"
