---
- name: Send ssh key
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Create directory
      file:
        path: .ssh/authorized_keys
        state: directory
    
    - name: Send ssh key
      file:
        path: cat /Users/lucasvasconcelos/authorized_keys.txt "cat >> .ssh/authorized_keys"
        state: absent
