---
- name: Send ssh key
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: true
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Send ssh key
      shell:: cat /Users/lucasvasconcelos/authorized_keys.txt | ssh br11556@m{{ operations_hosts_inventory }} "mkdir -p .ssh; cat >> .ssh/authorized_keys"
