---
- name: Send ssh key
  hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  
  tasks:
    - name: Send ssh key
      file:
        path: cat /Users/lucasvasconcelos/authorized_keys.txt | ssh br11556@m{{ operations_hosts_inventory }} "mkdir -p .ssh; cat >> .ssh/authorized_keys"
        state: directory
